# Generated by Django 4.1.1 on 2022-11-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='orig_name',
        ),
    ]
